Add new curves: f1 and p1
Som-Energia/heman pull request #1
Opened 2020-05-08 06:33 UTC by BenjiRS94

# **Changes**

Added curves f1 and p1 at the CCHFACT end point:
If the CUPS has f5d curves, return only f5d curves.
If has f1 and p1 merge two types of curves. In this case, the F1 will have priority because they are consolidated.

# **Refactors**
Extract some funcions in same CCHFACT class

# **Tests**

2020-05-15 09:07 UTC, juan-pe requested changes
Merci por el curro!!
@BenjiRS94 @MarJene podeu revisar los comentarios a ver que os parece?? 

Un saludo!!

2020-05-15 09:07 UTC, juan-pe commented on heman/api/cch/__init__.py
> +        p1_search_query = {
`p1_search_query` es igual que `search_query`. os propongo lo siguiente
quitar `p1_search_query` y cambiar la sentencia `cursor_p1 = self.get_cursor_db(collection='tg_p1', query=p1_search_query)` por:

```python
cursor_p1 = self.get_cursor_db(collection='tg_p1', query=search_query.update({'type': 'p'})
```

2020-05-15 09:07 UTC, juan-pe commented on heman/api/cch/__init__.py
> +            for item in cursor_f5d:
pienso que si `item` fuera `curve` le daria un poco mas de significado

2020-05-15 09:07 UTC, juan-pe commented on heman/api/cch/__init__.py
> +    def ordered_merge(self, cursor_f1, cursor_p1):
os propongo el sigueinte refactor para esta función
```python
    def _curve_value(self, curve):
        return {
            'date': time.mktime((curve['datetime']).timetuple()) * 1000,
            'value': curve['ai']
        }

    def ordered_merge(self, cursor_f1, cursor_p1):
        res = []
        f1_curve = next(cursor_f1, False)
        p1_curve = next(cursor_p1, False)
        while f1_curve and p1_curve:
            if f1_curve['datetime'] == p1_curve['datetime']:
                res += [_curve_value(f1_curve)]
                f1_curve = next(cursor_f1, False)
                p1_curve = next(cursor_p1, False)
            elif f1_curve['datetime'] < p1_curve['datetime']:
                res += [_curve_value(f1_curve)]
                f1_curve = next(cursor_f1, False)
            else:
                res += [_curve_value(p1_curve)]
                p1_curve = next(cursor_p1, False)

        while item_f1:
            res += [_curve_value(f1_curve)]
            f1_curve = next(cursor_f1, False)
        while item_p1:
            res += [_curve_value(p1_curve)]
            p1_curve = next(cursor_p1, False)

        return res
```

2020-05-15 09:07 UTC, juan-pe commented on heman/api/cch/__init__.py
> +    def ordered_merge(self, cursor_f1, cursor_p1):
tambien no me termina de el patrón de whiles e ifs, pero no os puedo proponer otra cosa porque no se me ocurre... :sweat_smile: :sweat_smile:

2020-05-20 06:10 UTC, BenjiRS94 commented on heman/api/cch/__init__.py
> +        p1_search_query = {
Muy buena idea no se nos habia ocurrido!

2020-05-20 08:59 UTC, BenjiRS94 commented on heman/api/cch/__init__.py
> +    def ordered_merge(self, cursor_f1, cursor_p1):
Lo he probado y el rendimiento ha bajado bastante (la peticion no puede acabar de lo que tarda el while)

2020-05-20 13:43 UTC, juan-pe commented on heman/api/cch/__init__.py
> +    def ordered_merge(self, cursor_f1, cursor_p1):
podemos cambiar el ```res += [_curve_value(f1_curve)]``` por el ```res.append(_curve_value(f1_curve))``` ??

2020-05-25 06:11 UTC, juan-pe approved these changes
:+1: :ok_hand:

2020-05-25 12:01 UTC, merged