Add infoenergia reports
Som-Energia/heman pull request #2
Opened 2020-12-21 08:45 UTC by marta197

- Add `api/InfoenergiaReport/{contract_id}` endpoint to extract infoenergia reports from mongo.

Request example:
```
 headers: {
    'Authorization': token
  }
```

2020-12-21 13:46 UTC, juan-pe requested changes
Easy right?? :smile: 
if you can delete the imports that aren't used, this code is perfect!

thanks a lot!

2020-12-21 13:46 UTC, juan-pe commented on heman/api/infoenergia/__init__.py
> +
`datetime`, `relativedelta`, `time`, `request` and `ASCENDING` imports are not used :fearful: :laughing: :laughing:

2020-12-22 10:25 UTC, marta197 commented on heman/api/infoenergia/__init__.py
> +
Good you noticed it!! It'll be fixed on the next commit. Thank you! :smile:

2020-12-22 10:26 UTC, juan-pe approved these changes
:+1: fantastic!

2021-02-03 13:31 UTC, merged